Implement Logic for Missing Glitches
icebound777/PMR-SeedGenerator pull request #106
Opened 2024-04-25 06:23 UTC by Phantom5800

Implementing a handful of glitches that do not currently exist in the glitch logic list.

2024-04-29 17:31 UTC, icebound777 reviewed
Note to self: Discuss with others whether Prolog Stone Block should be multiple settings instead

2024-04-29 17:35 UTC, icebound777 reviewed
Pointed at a few problems

2024-04-29 17:35 UTC, icebound777 commented on maps/graph_edges/glitched_logic/isk_ruins_stone_skip.py
> +edges_pra_add_ruins_stone_skip= [
edges_pra should be edges_isk

2024-04-29 17:35 UTC, icebound777 commented on rando_modules/modify_entrances.py
> +    if glitch_settings.mirror_clip:
Same settings used twice, probably meant `glitch_settings.pra_kooper_puzzle_skip`

2024-04-29 17:35 UTC, icebound777 commented on rando_modules/modify_entrances.py
> +        all_new_edges.extned(edges_pra_add_kooper_puzzle_skip)
Code typo, won't run

2024-04-30 19:13 UTC, Phantom5800 commented
I considered adding a bunch of jumpless tricks, but may do a separate one for those in particular down the line.

2024-05-07 07:42 UTC, Pronyo-Chan commented
lgtm

2024-05-11 15:41 UTC, icebound777 commented
Please set target branch to the dev branch instead of the main branch. Main branch is for current website state only

2024-05-12 19:59 UTC, Phantom5800 commented
Tried rebasing on dev and just ended up cherry picking commits instead because it kept pulling in bps changes from somewhere

2024-05-14 19:49 UTC, icebound777 commented on maps/graph_edges/glitched_logic/omo_wattless_dark_room.py
> +for Glitched Logic: ToyBox Blue Switch Skip.
referenced glitch incorrect

2024-05-15 10:21 UTC, icebound777 commented
Would you like this PR to be merged ASAP, or keep it open until we're ready for another release? In case you feel like adding more glitch settings

2024-05-15 11:28 UTC, Phantom5800 commented
This is fine to merge whenever. I wasn't planning on adding anything else.

2024-05-19 16:29 UTC, icebound777 commented
About the ruins stone skip: I seem to remember something about the padlock in that room influencing the possibility of doing this trick, or maybe making it harder if the padlock was opened already. What was up with that again?

2024-05-20 07:09 UTC, Phantom5800 commented
> About the ruins stone skip: I seem to remember something about the padlock in that room influencing the possibility of doing this trick, or maybe making it harder if the padlock was opened already. What was up with that again?

It's a lot easier to do with the lock still there because mario is able to move without laki following him as long as the exclamation point is above his head. It's possible to do in a different spot otherwise, but there isn't as good of a setup for it.

2024-05-26 12:44 UTC, icebound777 requested changes
Did a local checkout of the PR, found some issues

2024-06-03 20:40 UTC, Phantom5800 commented on maps/graph_edges/glitched_logic/omo_clippy_green_station_coin_block.py
> +    (0xA1100840, {"from": {"map": "OMO_09", "id": "ItemH"}, "to": {"map": "OMO_09", "id": "RandomBlockItemA"}, "reqs": [["Lakilester"],["Boots"]], "mapchange": False})
this one I wasn't sure of but makes sense why boots wouldn't be required for this particular edge

2024-06-05 16:02 UTC, icebound777 approved these changes
`Dry Dry Ruins Stone Skip` currently does nothing in logic, due to a bug in the base graph, will fix that post merge. Otherwise lgtm

2024-06-05 16:03 UTC, merged