Random stats based on starting level
icebound777/PMR-SeedGenerator pull request #113
Opened 2024-11-04 12:11 UTC by Phantom5800

If `StartingLevel` is provided and is a valid level from 0-27, randomly distribute stats.

2024-11-07 18:15 UTC, icebound777 commented
At the point where the OptionsSet is being built the seeding for randomization is not initialized yet.
That happens in `random_seed.py`, and only afterwards the randint function can be used deterministically for us.
Since the random starting stats do not influence the logic currently, I recommend calling that code somewhere after the `Generation attempt` loop in `random_seed.py`. Preferably outsourced into its own file within the `rando_modules` directory.

2024-11-15 21:54 UTC, Phantom5800 commented
Marking as ready for review after verifying changes myself across a handful of seeds.

2025-01-16 09:58 UTC, icebound777 requested changes
Review: a few small things

2025-01-16 09:58 UTC, icebound777 commented on models/options/OptionSet.py
> +from random import randint
Please remove unused import

2025-01-16 09:58 UTC, icebound777 commented on models/options/OptionSet.py
> +        self.starting_level = self.random_starting_level = get_option_default_value("StartingLevel")
This might not work as expected, please verify.
`get_option_default_value()` reads data from the sqlite db in the root dir, and that db gets built from the base rom data.
This default value is used if the associated key is not provided within the settings yaml.
The base rom sets StartingLevel to 1, so this might mess with random starting levels if no StartingLevel keyvalue pair is provided.

2025-01-16 09:58 UTC, icebound777 commented on rando_modules/random_stat_distribution.py
> +def generate_random_stats(level: int):
Please add type hint for return values here

2025-01-17 20:25 UTC, icebound777 reviewed
Minor Copy & Paste error in settings files, after that lgtm

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_AllChaptersRaceS1.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_Beginner.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_BlitzRaceS2.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_BlitzRaceS3.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_ExtremeShuffle.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_Intermediate.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-17 20:25 UTC, icebound777 commented on presets/preset_OpenWorld.yaml
> +StartingCoins           : 50
Starting Coins: Copy & Paste error

2025-01-19 13:03 UTC, icebound777 approved these changes

2025-01-19 13:04 UTC, merged